using Battlehub.RTEditor.ViewModels;
using UnityWeld.Binding;

namespace Battlehub.RTEditor.Examples.Scene6.ViewModels
{
	//This is ViewModel (see https://github.com/Real-Serious-Games/Unity-Weld/wiki for details). Autogenerated using Tools > RuntimeEditor > Create Custom Window in the UnityEditor main menu
	[Binding]
	public class CustomExampleViewModel : ViewModel
	{
		[Binding]
		public string Text
		{
			get { return "This is an example of a custom window. To create your own, \n click Tools > RuntimeEditor > Create Custom Window \n in the main menu of Unity Editor."; }	
		}

		protected override void Start()
		{
			base.Start();
		}
	}
}


