using Battlehub.RTCommon;
using Battlehub.RTEditor;
using Battlehub.UIControls.MenuControl;
using UnityEngine;

namespace Battlehub.RTEditor.Examples.Scene6
{
	/// <summary>
	/// This is custom window registration script. Autogenerated using Tools > RuntimeEditor > Create Custom Window in the UnityEditor main menu
	/// </summary>
	[MenuDefinition]
	public class RegisterCustomExampleWindow : EditorExtension
	{
		[SerializeField]
		private GameObject m_prefab = null;

		[SerializeField]
		private Sprite m_icon = null;
		
		[SerializeField]
		private string m_header = "CustomExample";

		[SerializeField]
		private bool m_isDialog = false;

		[SerializeField]
		private int m_maxWindows = -1;

		protected override void OnInit()
		{
			base.OnInit();

			IWindowManager wm = IOC.Resolve<IWindowManager>();
			wm.RegisterWindow("CustomExample", m_header, m_icon, m_prefab, m_isDialog, m_maxWindows);
		}

		[MenuCommand("MenuWindow/Custom Window", "", 0)]
		public void Open()
		{
			IWindowManager wm = IOC.Resolve<IWindowManager>();
			wm.CreateWindow("CustomExample");
		}
	}
}



